### ISSUE TITLE
Dockerize Surabaya

### ISSUE THREAD

**Issue by algobot76** [algobot76/surabaya#63]
Integrate Surabaya with Docker so that we can easily run the application on any platform.

**Comment by pratikbalar123** [comment]
Done, [HERE](https://github.com/pratikbalar123/surabaya). with automated image pushing to [my Docker hub repo](https://hub.docker.com/repositories) on every push and pull, you can also make it push to images to GitHub packages.

**Comment by pratikbalar123** [comment]
Done, [HERE](https://github.com/pratikbalar123/surabaya). with GH Actions for image pushing to [my Docker hub repo](https://hub.docker.com/repository/docker/pratikbalar123/dockered-surabaya), you can also push images to GitHub packages.
