### ISSUE TITLE
Implement static code analysis for a single file

### ISSUE THREAD

**Issue by ZhiHanL** [algobot76/surabaya#7]
Create a method that spits out the data structure outlined in the README for an input Java src directory by using the JavaParser Library, converting its output and performing any additional analysis.

**Comment by algobot76** [comment]
Personally, I think this issue is too big. Maybe we could split it into smaller issues?

**Comment by ZhiHanL** [comment]
Okay, though I'm pretty much done. I have it working for a single file, just need to add support for a whole project
