### ISSUE TITLE
Render method / ctor's source code in React (upon hover? upon island click?)

### ISSUE THREAD

**Issue by john-zou** [algobot76/surabaya#90]
Back end prerequisite: #89

**Comment by algobot76** [comment]
It could be an interesting feature to be added to the project. However, I think we should focus on other issues for now because this feature will bring breaking changes to the codebase and we may not have enough time to implement it before the deadline.

**Comment by john-zou** [comment]
I just did the back end for it without breaking changes

**Comment by john-zou** [comment]
Closing because this issue is #100
